config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'lists#home'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "It is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def home
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>All lists</h1>

  <ul>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>

  <p> <%= link_to 'Create a movie list', new_list_path %> </p>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

</div>

app/views/lists/show.html.erb
<div class="container">
  <h1> <%= @list.name %> </h1>
  <div>
    <ul>
      <% @list.bookmarks.each do |bookmark| %>
      <li> <strong>Comment:</strong> <%= bookmark.comment %> </li>
      <li> <strong>Movie:</strong> <%= bookmark.movie.title %></li>
      <li> <strong> Rating:</strong> <%= bookmark.movie.rating %> </li>
      <li> <strong>Poster_url:</strong> <%= bookmark.movie.poster_url %> </li>
      <li> <strong>Overview:</strong> <%= bookmark.movie.overview %> </li>
      <hr>
      <% end %>
    </ul>
  </div>
  <p> <%= link_to 'Add a new movie', new_list_bookmark_path(@list) %> </p>
  <p> <%= link_to 'Back to all lists', lists_path %> </p>

</div>